[build]
target = "riscv32imac-unknown-none-elf"

[target.riscv32imac-unknown-none-elf]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Tlinker.ld",      # 使用自定义链接脚本
    "-C", "relocation-model=static",   # 使用静态重定位模式
    "-C", "target-feature=-crt-static", # 禁用静态C运行时
]

[unstable]
build-std = ["core"]                 # 只构建core库，不包含std和alloc
build-std-features = ["compiler-builtins-mem"] # 启用编译器内建的内存操作函数